[theme]
# Modern Financial App Theme
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
linkColor = "#2563eb"
linkUnderline = false
codeBackgroundColor = "#f1f5f9"
font = "sans-serif"
headingFont = "sans-serif"
baseRadius = "0.5rem"
borderColor = "#e2e8f0"
showWidgetBorder = true
baseFontSize = 16

[theme.sidebar]
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#000000"
primaryColor = "#60a5fa"
linkColor = "#93c5fd"
borderColor = "#334155"